# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextBrowser, QTextEdit,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(592, 649)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionEmbed = QAction(MainWindow)
        self.actionEmbed.setObjectName(u"actionEmbed")
        self.actionImport_Design = QAction(MainWindow)
        self.actionImport_Design.setObjectName(u"actionImport_Design")
        self.actionExport_Design = QAction(MainWindow)
        self.actionExport_Design.setObjectName(u"actionExport_Design")
        self.actionShow_Errors = QAction(MainWindow)
        self.actionShow_Errors.setObjectName(u"actionShow_Errors")
        self.actionShow_Errors.setCheckable(True)
        self.actionShow_Errors.setChecked(False)
        self.actionShow_Figure = QAction(MainWindow)
        self.actionShow_Figure.setObjectName(u"actionShow_Figure")
        self.actionSave_all_Figure = QAction(MainWindow)
        self.actionSave_all_Figure.setObjectName(u"actionSave_all_Figure")
        self.actionSave_results_to_HDF5 = QAction(MainWindow)
        self.actionSave_results_to_HDF5.setObjectName(u"actionSave_results_to_HDF5")
        self.actionReset_DYT = QAction(MainWindow)
        self.actionReset_DYT.setObjectName(u"actionReset_DYT")
        self.actionSettingsConstants = QAction(MainWindow)
        self.actionSettingsConstants.setObjectName(u"actionSettingsConstants")
        self.actionSave_equil_to_EQDSK = QAction(MainWindow)
        self.actionSave_equil_to_EQDSK.setObjectName(u"actionSave_equil_to_EQDSK")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabDYT = QTabWidget(self.centralwidget)
        self.tabDYT.setObjectName(u"tabDYT")
        self.tabDYT.setEnabled(True)
        self.tabDYT.setGeometry(QRect(10, 20, 561, 571))
        font = QFont()
        font.setFamilies([u".AppleSystemUIFont"])
        self.tabDYT.setFont(font)
        self.tabDYT.setMouseTracking(False)
        self.tabDYT.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.page_general = QWidget()
        self.page_general.setObjectName(u"page_general")
        self.groupBox = QGroupBox(self.page_general)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 531, 131))
        self.box_np48 = QLineEdit(self.groupBox)
        self.box_np48.setObjectName(u"box_np48")
        self.box_np48.setEnabled(True)
        self.box_np48.setGeometry(QRect(130, 30, 61, 25))
        self.box_np48.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.box_np48.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.box_np48.setAutoFillBackground(True)
        self.box_np48.setStyleSheet(u"")
        self.box_np48.setMaxLength(32767)
        self.box_np48.setFrame(True)
        self.box_np48.setCursorPosition(0)
        self.box_np48.setDragEnabled(True)
        self.box_np48.setReadOnly(False)
        self.box_np48.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.box_np48.setClearButtonEnabled(False)
        self.box_nn48 = QLineEdit(self.groupBox)
        self.box_nn48.setObjectName(u"box_nn48")
        self.box_nn48.setGeometry(QRect(130, 60, 61, 25))
        self.box_nn48.setAutoFillBackground(True)
        self.box_nn48.setStyleSheet(u"")
        self.box_nn48.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.box_nn48.setMaxLength(32767)
        self.box_nn48.setDragEnabled(True)
        self.box_np40 = QLineEdit(self.groupBox)
        self.box_np40.setObjectName(u"box_np40")
        self.box_np40.setGeometry(QRect(380, 30, 61, 25))
        self.box_np40.setAutoFillBackground(True)
        self.box_np40.setStyleSheet(u"")
        self.box_np40.setMaxLength(32767)
        self.box_np40.setDragEnabled(True)
        self.box_nn40 = QLineEdit(self.groupBox)
        self.box_nn40.setObjectName(u"box_nn40")
        self.box_nn40.setGeometry(QRect(380, 60, 61, 25))
        self.box_nn40.setAutoFillBackground(True)
        self.box_nn40.setStyleSheet(u"")
        self.box_nn40.setMaxLength(32767)
        self.box_nn40.setDragEnabled(True)
        self.box_pp40 = QLineEdit(self.groupBox)
        self.box_pp40.setObjectName(u"box_pp40")
        self.box_pp40.setGeometry(QRect(380, 90, 61, 25))
        self.box_pp40.setAutoFillBackground(True)
        self.box_pp40.setStyleSheet(u"")
        self.box_pp40.setMaxLength(32767)
        self.box_pp40.setDragEnabled(True)
        self.label_np48 = QLabel(self.groupBox)
        self.label_np48.setObjectName(u"label_np48")
        self.label_np48.setGeometry(QRect(50, 30, 71, 21))
        font1 = QFont()
        font1.setFamilies([u".AppleSystemUIFont"])
        font1.setPointSize(9)
        self.label_np48.setFont(font1)
        self.label_np48.setScaledContents(True)
        self.label_nn48 = QLabel(self.groupBox)
        self.label_nn48.setObjectName(u"label_nn48")
        self.label_nn48.setGeometry(QRect(50, 60, 71, 21))
        self.label_nn48.setFont(font1)
        self.label_nn48.setScaledContents(True)
        self.label_np40 = QLabel(self.groupBox)
        self.label_np40.setObjectName(u"label_np40")
        self.label_np40.setGeometry(QRect(300, 30, 71, 21))
        self.label_np40.setFont(font1)
        self.label_np40.setScaledContents(False)
        self.label_nn40 = QLabel(self.groupBox)
        self.label_nn40.setObjectName(u"label_nn40")
        self.label_nn40.setGeometry(QRect(300, 60, 71, 21))
        self.label_nn40.setFont(font1)
        self.label_nn40.setScaledContents(False)
        self.label_pp40 = QLabel(self.groupBox)
        self.label_pp40.setObjectName(u"label_pp40")
        self.label_pp40.setGeometry(QRect(300, 90, 71, 21))
        self.label_pp40.setFont(font1)
        self.label_pp40.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.label_pp40.setTextFormat(Qt.TextFormat.PlainText)
        self.label_pp40.setScaledContents(False)
        self.label_pp40.setIndent(4)
        self.label_pp48 = QLabel(self.groupBox)
        self.label_pp48.setObjectName(u"label_pp48")
        self.label_pp48.setGeometry(QRect(50, 90, 71, 21))
        self.label_pp48.setFont(font1)
        self.label_pp48.setScaledContents(True)
        self.box_pp48 = QLineEdit(self.groupBox)
        self.box_pp48.setObjectName(u"box_pp48")
        self.box_pp48.setGeometry(QRect(130, 90, 61, 25))
        self.box_pp48.setAutoFillBackground(True)
        self.box_pp48.setStyleSheet(u"")
        self.box_pp48.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.box_pp48.setMaxLength(32767)
        self.box_pp48.setDragEnabled(True)
        self.button_findratio = QPushButton(self.page_general)
        self.button_findratio.setObjectName(u"button_findratio")
        self.button_findratio.setGeometry(QRect(230, 160, 113, 32))
        self.ratio_output = QTextBrowser(self.page_general)
        self.ratio_output.setObjectName(u"ratio_output")
        self.ratio_output.setGeometry(QRect(20, 210, 521, 121))
        self.buttonSaveRatios = QPushButton(self.page_general)
        self.buttonSaveRatios.setObjectName(u"buttonSaveRatios")
        self.buttonSaveRatios.setGeometry(QRect(230, 350, 113, 32))
        self.box_RATIOname = QLineEdit(self.page_general)
        self.box_RATIOname.setObjectName(u"box_RATIOname")
        self.box_RATIOname.setGeometry(QRect(130, 350, 91, 21))
        self.label_RatioName = QLabel(self.page_general)
        self.label_RatioName.setObjectName(u"label_RatioName")
        self.label_RatioName.setGeometry(QRect(40, 350, 81, 20))
        self.btn_clear_1 = QPushButton(self.page_general)
        self.btn_clear_1.setObjectName(u"btn_clear_1")
        self.btn_clear_1.setGeometry(QRect(350, 160, 81, 32))
        self.left_1 = QPushButton(self.page_general)
        self.left_1.setObjectName(u"left_1")
        self.left_1.setGeometry(QRect(70, 160, 31, 32))
        self.right_1 = QPushButton(self.page_general)
        self.right_1.setObjectName(u"right_1")
        self.right_1.setGeometry(QRect(110, 160, 31, 32))
        self.model_label1 = QLabel(self.page_general)
        self.model_label1.setObjectName(u"model_label1")
        self.model_label1.setGeometry(QRect(150, 170, 61, 20))
        self.tabDYT.addTab(self.page_general, "")
        self.page_PFcoils = QWidget()
        self.page_PFcoils.setObjectName(u"page_PFcoils")
        self.page_PFcoils.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.groupBox_2 = QGroupBox(self.page_PFcoils)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 531, 241))
        self.Reep = QLineEdit(self.groupBox_2)
        self.Reep.setObjectName(u"Reep")
        self.Reep.setEnabled(True)
        self.Reep.setGeometry(QRect(130, 30, 61, 25))
        self.Reep.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Reep.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Reep.setAutoFillBackground(True)
        self.Reep.setStyleSheet(u"")
        self.Reep.setMaxLength(32767)
        self.Reep.setFrame(True)
        self.Reep.setCursorPosition(0)
        self.Reep.setDragEnabled(True)
        self.Reep.setReadOnly(False)
        self.Reep.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.Reep.setClearButtonEnabled(False)
        self.Ree = QLineEdit(self.groupBox_2)
        self.Ree.setObjectName(u"Ree")
        self.Ree.setGeometry(QRect(130, 60, 61, 25))
        self.Ree.setAutoFillBackground(True)
        self.Ree.setStyleSheet(u"")
        self.Ree.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.Ree.setMaxLength(32767)
        self.Ree.setDragEnabled(True)
        self.Reen = QLineEdit(self.groupBox_2)
        self.Reen.setObjectName(u"Reen")
        self.Reen.setGeometry(QRect(380, 30, 61, 25))
        self.Reen.setAutoFillBackground(True)
        self.Reen.setStyleSheet(u"")
        self.Reen.setMaxLength(32767)
        self.Reen.setDragEnabled(True)
        self.Reepp = QLineEdit(self.groupBox_2)
        self.Reepp.setObjectName(u"Reepp")
        self.Reepp.setGeometry(QRect(380, 60, 61, 25))
        self.Reepp.setAutoFillBackground(True)
        self.Reepp.setStyleSheet(u"")
        self.Reepp.setMaxLength(32767)
        self.Reepp.setDragEnabled(True)
        self.label_np48_2 = QLabel(self.groupBox_2)
        self.label_np48_2.setObjectName(u"label_np48_2")
        self.label_np48_2.setGeometry(QRect(50, 30, 71, 21))
        self.label_np48_2.setFont(font1)
        self.label_np48_2.setScaledContents(True)
        self.label_nn48_2 = QLabel(self.groupBox_2)
        self.label_nn48_2.setObjectName(u"label_nn48_2")
        self.label_nn48_2.setGeometry(QRect(50, 60, 71, 21))
        self.label_nn48_2.setFont(font1)
        self.label_nn48_2.setScaledContents(True)
        self.label_np40_2 = QLabel(self.groupBox_2)
        self.label_np40_2.setObjectName(u"label_np40_2")
        self.label_np40_2.setGeometry(QRect(300, 30, 71, 20))
        self.label_np40_2.setFont(font1)
        self.label_np40_2.setScaledContents(False)
        self.label_nn40_2 = QLabel(self.groupBox_2)
        self.label_nn40_2.setObjectName(u"label_nn40_2")
        self.label_nn40_2.setGeometry(QRect(300, 60, 71, 21))
        self.label_nn40_2.setFont(font1)
        self.label_nn40_2.setScaledContents(False)
        self.label_pp48_2 = QLabel(self.groupBox_2)
        self.label_pp48_2.setObjectName(u"label_pp48_2")
        self.label_pp48_2.setGeometry(QRect(50, 90, 71, 21))
        self.label_pp48_2.setFont(font1)
        self.label_pp48_2.setScaledContents(True)
        self.Reenp = QLineEdit(self.groupBox_2)
        self.Reenp.setObjectName(u"Reenp")
        self.Reenp.setGeometry(QRect(130, 90, 61, 25))
        self.Reenp.setAutoFillBackground(True)
        self.Reenp.setStyleSheet(u"")
        self.Reenp.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.Reenp.setMaxLength(32767)
        self.Reenp.setDragEnabled(True)
        self.label_np40_3 = QLabel(self.groupBox_2)
        self.label_np40_3.setObjectName(u"label_np40_3")
        self.label_np40_3.setGeometry(QRect(300, 170, 71, 21))
        self.label_np40_3.setFont(font1)
        self.label_np40_3.setScaledContents(False)
        self.ppp40 = QLineEdit(self.groupBox_2)
        self.ppp40.setObjectName(u"ppp40")
        self.ppp40.setGeometry(QRect(130, 200, 61, 25))
        self.ppp40.setAutoFillBackground(True)
        self.ppp40.setStyleSheet(u"")
        self.ppp40.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.ppp40.setMaxLength(32767)
        self.ppp40.setDragEnabled(True)
        self.label_nn40_3 = QLabel(self.groupBox_2)
        self.label_nn40_3.setObjectName(u"label_nn40_3")
        self.label_nn40_3.setGeometry(QRect(300, 200, 71, 21))
        self.label_nn40_3.setFont(font1)
        self.label_nn40_3.setScaledContents(False)
        self.ppp48 = QLineEdit(self.groupBox_2)
        self.ppp48.setObjectName(u"ppp48")
        self.ppp48.setEnabled(True)
        self.ppp48.setGeometry(QRect(130, 170, 61, 25))
        self.ppp48.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.ppp48.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ppp48.setAutoFillBackground(True)
        self.ppp48.setStyleSheet(u"")
        self.ppp48.setMaxLength(32767)
        self.ppp48.setFrame(True)
        self.ppp48.setCursorPosition(0)
        self.ppp48.setDragEnabled(True)
        self.ppp48.setReadOnly(False)
        self.ppp48.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.ppp48.setClearButtonEnabled(False)
        self.label_np48_3 = QLabel(self.groupBox_2)
        self.label_np48_3.setObjectName(u"label_np48_3")
        self.label_np48_3.setGeometry(QRect(50, 170, 71, 21))
        self.label_np48_3.setFont(font1)
        self.label_np48_3.setScaledContents(True)
        self.npn40 = QLineEdit(self.groupBox_2)
        self.npn40.setObjectName(u"npn40")
        self.npn40.setGeometry(QRect(380, 200, 61, 25))
        self.npn40.setAutoFillBackground(True)
        self.npn40.setStyleSheet(u"")
        self.npn40.setMaxLength(32767)
        self.npn40.setDragEnabled(True)
        self.npn48 = QLineEdit(self.groupBox_2)
        self.npn48.setObjectName(u"npn48")
        self.npn48.setGeometry(QRect(380, 170, 61, 25))
        self.npn48.setAutoFillBackground(True)
        self.npn48.setStyleSheet(u"")
        self.npn48.setMaxLength(32767)
        self.npn48.setDragEnabled(True)
        self.label_nn48_3 = QLabel(self.groupBox_2)
        self.label_nn48_3.setObjectName(u"label_nn48_3")
        self.label_nn48_3.setGeometry(QRect(50, 200, 71, 21))
        self.label_nn48_3.setFont(font1)
        self.label_nn48_3.setScaledContents(True)
        self.line_3 = QFrame(self.groupBox_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 130, 491, 16))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.pn_output = QTextBrowser(self.page_PFcoils)
        self.pn_output.setObjectName(u"pn_output")
        self.pn_output.setGeometry(QRect(20, 300, 511, 121))
        self.button_findpn = QPushButton(self.page_PFcoils)
        self.button_findpn.setObjectName(u"button_findpn")
        self.button_findpn.setGeometry(QRect(210, 260, 151, 32))
        self.buttonSavePN = QPushButton(self.page_PFcoils)
        self.buttonSavePN.setObjectName(u"buttonSavePN")
        self.buttonSavePN.setGeometry(QRect(230, 430, 113, 32))
        self.label_NPname = QLabel(self.page_PFcoils)
        self.label_NPname.setObjectName(u"label_NPname")
        self.label_NPname.setGeometry(QRect(40, 430, 81, 20))
        self.box_PNname = QLineEdit(self.page_PFcoils)
        self.box_PNname.setObjectName(u"box_PNname")
        self.box_PNname.setGeometry(QRect(130, 430, 91, 21))
        self.btn_clear_2 = QPushButton(self.page_PFcoils)
        self.btn_clear_2.setObjectName(u"btn_clear_2")
        self.btn_clear_2.setGeometry(QRect(370, 260, 81, 32))
        self.left_2 = QPushButton(self.page_PFcoils)
        self.left_2.setObjectName(u"left_2")
        self.left_2.setGeometry(QRect(50, 260, 31, 32))
        self.right_2 = QPushButton(self.page_PFcoils)
        self.right_2.setObjectName(u"right_2")
        self.right_2.setGeometry(QRect(90, 260, 31, 32))
        self.tabDYT.addTab(self.page_PFcoils, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_3 = QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 531, 241))
        self.Reep_2 = QLineEdit(self.groupBox_3)
        self.Reep_2.setObjectName(u"Reep_2")
        self.Reep_2.setEnabled(True)
        self.Reep_2.setGeometry(QRect(130, 30, 61, 25))
        self.Reep_2.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.Reep_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Reep_2.setAutoFillBackground(True)
        self.Reep_2.setStyleSheet(u"")
        self.Reep_2.setMaxLength(32767)
        self.Reep_2.setFrame(True)
        self.Reep_2.setCursorPosition(4)
        self.Reep_2.setDragEnabled(True)
        self.Reep_2.setReadOnly(False)
        self.Reep_2.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.Reep_2.setClearButtonEnabled(False)
        self.Ree_2 = QLineEdit(self.groupBox_3)
        self.Ree_2.setObjectName(u"Ree_2")
        self.Ree_2.setGeometry(QRect(130, 60, 61, 25))
        self.Ree_2.setAutoFillBackground(True)
        self.Ree_2.setStyleSheet(u"")
        self.Ree_2.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.Ree_2.setMaxLength(32767)
        self.Ree_2.setDragEnabled(True)
        self.Reen_2 = QLineEdit(self.groupBox_3)
        self.Reen_2.setObjectName(u"Reen_2")
        self.Reen_2.setGeometry(QRect(380, 30, 61, 25))
        self.Reen_2.setAutoFillBackground(True)
        self.Reen_2.setStyleSheet(u"")
        self.Reen_2.setMaxLength(32767)
        self.Reen_2.setDragEnabled(True)
        self.Reepp_2 = QLineEdit(self.groupBox_3)
        self.Reepp_2.setObjectName(u"Reepp_2")
        self.Reepp_2.setGeometry(QRect(380, 60, 61, 25))
        self.Reepp_2.setAutoFillBackground(True)
        self.Reepp_2.setStyleSheet(u"")
        self.Reepp_2.setMaxLength(32767)
        self.Reepp_2.setDragEnabled(True)
        self.label_np48_4 = QLabel(self.groupBox_3)
        self.label_np48_4.setObjectName(u"label_np48_4")
        self.label_np48_4.setGeometry(QRect(50, 30, 71, 21))
        self.label_np48_4.setFont(font1)
        self.label_np48_4.setScaledContents(True)
        self.label_nn48_4 = QLabel(self.groupBox_3)
        self.label_nn48_4.setObjectName(u"label_nn48_4")
        self.label_nn48_4.setGeometry(QRect(50, 60, 71, 21))
        self.label_nn48_4.setFont(font1)
        self.label_nn48_4.setScaledContents(True)
        self.label_np40_4 = QLabel(self.groupBox_3)
        self.label_np40_4.setObjectName(u"label_np40_4")
        self.label_np40_4.setGeometry(QRect(300, 30, 71, 20))
        self.label_np40_4.setFont(font1)
        self.label_np40_4.setScaledContents(False)
        self.label_nn40_4 = QLabel(self.groupBox_3)
        self.label_nn40_4.setObjectName(u"label_nn40_4")
        self.label_nn40_4.setGeometry(QRect(300, 60, 71, 21))
        self.label_nn40_4.setFont(font1)
        self.label_nn40_4.setScaledContents(False)
        self.label_pp48_3 = QLabel(self.groupBox_3)
        self.label_pp48_3.setObjectName(u"label_pp48_3")
        self.label_pp48_3.setGeometry(QRect(50, 90, 71, 21))
        self.label_pp48_3.setFont(font1)
        self.label_pp48_3.setScaledContents(True)
        self.Reenp_2 = QLineEdit(self.groupBox_3)
        self.Reenp_2.setObjectName(u"Reenp_2")
        self.Reenp_2.setGeometry(QRect(130, 90, 61, 25))
        self.Reenp_2.setAutoFillBackground(True)
        self.Reenp_2.setStyleSheet(u"")
        self.Reenp_2.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.Reenp_2.setMaxLength(32767)
        self.Reenp_2.setDragEnabled(True)
        self.label_np40_5 = QLabel(self.groupBox_3)
        self.label_np40_5.setObjectName(u"label_np40_5")
        self.label_np40_5.setGeometry(QRect(300, 170, 71, 21))
        self.label_np40_5.setFont(font1)
        self.label_np40_5.setScaledContents(False)
        self.ppp40_2 = QLineEdit(self.groupBox_3)
        self.ppp40_2.setObjectName(u"ppp40_2")
        self.ppp40_2.setGeometry(QRect(130, 200, 61, 25))
        self.ppp40_2.setAutoFillBackground(True)
        self.ppp40_2.setStyleSheet(u"")
        self.ppp40_2.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.ppp40_2.setMaxLength(32767)
        self.ppp40_2.setDragEnabled(True)
        self.label_nn40_5 = QLabel(self.groupBox_3)
        self.label_nn40_5.setObjectName(u"label_nn40_5")
        self.label_nn40_5.setGeometry(QRect(300, 200, 71, 21))
        self.label_nn40_5.setFont(font1)
        self.label_nn40_5.setScaledContents(False)
        self.ppp48_2 = QLineEdit(self.groupBox_3)
        self.ppp48_2.setObjectName(u"ppp48_2")
        self.ppp48_2.setEnabled(True)
        self.ppp48_2.setGeometry(QRect(130, 170, 61, 25))
        self.ppp48_2.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.ppp48_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ppp48_2.setAutoFillBackground(True)
        self.ppp48_2.setStyleSheet(u"")
        self.ppp48_2.setMaxLength(32767)
        self.ppp48_2.setFrame(True)
        self.ppp48_2.setCursorPosition(0)
        self.ppp48_2.setDragEnabled(True)
        self.ppp48_2.setReadOnly(False)
        self.ppp48_2.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.ppp48_2.setClearButtonEnabled(False)
        self.label_np48_5 = QLabel(self.groupBox_3)
        self.label_np48_5.setObjectName(u"label_np48_5")
        self.label_np48_5.setGeometry(QRect(50, 170, 71, 21))
        self.label_np48_5.setFont(font1)
        self.label_np48_5.setScaledContents(True)
        self.npn40_2 = QLineEdit(self.groupBox_3)
        self.npn40_2.setObjectName(u"npn40_2")
        self.npn40_2.setGeometry(QRect(380, 200, 61, 25))
        self.npn40_2.setAutoFillBackground(True)
        self.npn40_2.setStyleSheet(u"")
        self.npn40_2.setMaxLength(32767)
        self.npn40_2.setDragEnabled(True)
        self.npn48_2 = QLineEdit(self.groupBox_3)
        self.npn48_2.setObjectName(u"npn48_2")
        self.npn48_2.setGeometry(QRect(380, 170, 61, 25))
        self.npn48_2.setAutoFillBackground(True)
        self.npn48_2.setStyleSheet(u"")
        self.npn48_2.setMaxLength(32767)
        self.npn48_2.setDragEnabled(True)
        self.label_nn48_5 = QLabel(self.groupBox_3)
        self.label_nn48_5.setObjectName(u"label_nn48_5")
        self.label_nn48_5.setGeometry(QRect(50, 200, 71, 21))
        self.label_nn48_5.setFont(font1)
        self.label_nn48_5.setScaledContents(True)
        self.line_2 = QFrame(self.groupBox_3)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 132, 491, 16))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.button_findpn_2 = QPushButton(self.tab_3)
        self.button_findpn_2.setObjectName(u"button_findpn_2")
        self.button_findpn_2.setGeometry(QRect(210, 260, 151, 32))
        self.pn_output_2 = QTextBrowser(self.tab_3)
        self.pn_output_2.setObjectName(u"pn_output_2")
        self.pn_output_2.setGeometry(QRect(20, 300, 511, 121))
        self.buttonSavePN_2 = QPushButton(self.tab_3)
        self.buttonSavePN_2.setObjectName(u"buttonSavePN_2")
        self.buttonSavePN_2.setGeometry(QRect(230, 430, 113, 32))
        self.label_NPname_2 = QLabel(self.tab_3)
        self.label_NPname_2.setObjectName(u"label_NPname_2")
        self.label_NPname_2.setGeometry(QRect(40, 430, 81, 20))
        self.box_PNname_2 = QLineEdit(self.tab_3)
        self.box_PNname_2.setObjectName(u"box_PNname_2")
        self.box_PNname_2.setGeometry(QRect(130, 430, 91, 21))
        self.btn_clear_3 = QPushButton(self.tab_3)
        self.btn_clear_3.setObjectName(u"btn_clear_3")
        self.btn_clear_3.setGeometry(QRect(370, 260, 81, 32))
        self.right_3 = QPushButton(self.tab_3)
        self.right_3.setObjectName(u"right_3")
        self.right_3.setGeometry(QRect(90, 260, 31, 32))
        self.left_3 = QPushButton(self.tab_3)
        self.left_3.setObjectName(u"left_3")
        self.left_3.setGeometry(QRect(50, 260, 31, 32))
        self.tabDYT.addTab(self.tab_3, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.scrollArea = QScrollArea(self.tab)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QRect(0, 0, 551, 701))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 549, 699))
        self.pn_table = QTableWidget(self.scrollAreaWidgetContents)
        if (self.pn_table.rowCount() < 8):
            self.pn_table.setRowCount(8)
        __qtablewidgetitem = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.pn_table.setVerticalHeaderItem(7, __qtablewidgetitem7)
        self.pn_table.setObjectName(u"pn_table")
        self.pn_table.setGeometry(QRect(0, 20, 541, 261))
        self.pn_table.setRowCount(8)
        self.ratio_table = QTableWidget(self.scrollAreaWidgetContents)
        if (self.ratio_table.rowCount() < 10):
            self.ratio_table.setRowCount(10)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(3, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(4, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(5, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(6, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(7, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(8, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.ratio_table.setVerticalHeaderItem(9, __qtablewidgetitem17)
        self.ratio_table.setObjectName(u"ratio_table")
        self.ratio_table.setGeometry(QRect(0, 310, 541, 221))
        self.ratio_table.setRowCount(10)
        self.label = QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 0, 121, 16))
        self.label_2 = QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(250, 290, 81, 16))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabDYT.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.rangeEdit = QLineEdit(self.tab_2)
        self.rangeEdit.setObjectName(u"rangeEdit")
        self.rangeEdit.setGeometry(QRect(300, 60, 113, 21))
        self.graphButton = QPushButton(self.tab_2)
        self.graphButton.setObjectName(u"graphButton")
        self.graphButton.setEnabled(True)
        self.graphButton.setGeometry(QRect(230, 160, 111, 41))
        self.calcType = QComboBox(self.tab_2)
        self.calcType.setObjectName(u"calcType")
        self.calcType.setGeometry(QRect(280, 30, 151, 21))
        self.calcType.setEditable(False)
        self.calcType.setFrame(True)
        self.calcType.setModelColumn(0)
        self.calcTypeLabel = QLabel(self.tab_2)
        self.calcTypeLabel.setObjectName(u"calcTypeLabel")
        self.calcTypeLabel.setGeometry(QRect(160, 30, 101, 16))
        self.rangeLabel = QLabel(self.tab_2)
        self.rangeLabel.setObjectName(u"rangeLabel")
        self.rangeLabel.setGeometry(QRect(160, 60, 101, 16))
        self.checkNormAtom = QCheckBox(self.tab_2)
        self.checkNormAtom.setObjectName(u"checkNormAtom")
        self.checkNormAtom.setEnabled(True)
        self.checkNormAtom.setGeometry(QRect(40, 240, 171, 20))
        self.checkNormAtom.setChecked(False)
        self.stepEdit = QLineEdit(self.tab_2)
        self.stepEdit.setObjectName(u"stepEdit")
        self.stepEdit.setGeometry(QRect(300, 90, 113, 21))
        self.stepLabel = QLabel(self.tab_2)
        self.stepLabel.setObjectName(u"stepLabel")
        self.stepLabel.setGeometry(QRect(160, 90, 101, 16))
        self.line = QFrame(self.tab_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 210, 521, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.exprLabel = QLabel(self.tab_2)
        self.exprLabel.setObjectName(u"exprLabel")
        self.exprLabel.setGeometry(QRect(160, 120, 101, 16))
        self.exprEdit = QLineEdit(self.tab_2)
        self.exprEdit.setObjectName(u"exprEdit")
        self.exprEdit.setGeometry(QRect(300, 120, 111, 31))
        self.textEdit = QTextEdit(self.tab_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 320, 551, 161))
        self.textEdit.setReadOnly(True)
        self.button = QPushButton(self.tab_2)
        self.button.setObjectName(u"button")
        self.button.setGeometry(QRect(400, 170, 100, 32))
        self.button_2 = QPushButton(self.tab_2)
        self.button_2.setObjectName(u"button_2")
        self.button_2.setGeometry(QRect(410, 200, 100, 32))
        self.tabDYT.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 592, 29))
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
#if QT_CONFIG(shortcut)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.tabDYT, self.Reep)
        QWidget.setTabOrder(self.Reep, self.Reen)
        QWidget.setTabOrder(self.Reen, self.Ree)
        QWidget.setTabOrder(self.Ree, self.Reepp)
        QWidget.setTabOrder(self.Reepp, self.Reenp)
        QWidget.setTabOrder(self.Reenp, self.ppp48)
        QWidget.setTabOrder(self.ppp48, self.npn48)
        QWidget.setTabOrder(self.npn48, self.ppp40)
        QWidget.setTabOrder(self.ppp40, self.npn40)
        QWidget.setTabOrder(self.npn40, self.pn_output)
        QWidget.setTabOrder(self.pn_output, self.box_np48)
        QWidget.setTabOrder(self.box_np48, self.box_np40)
        QWidget.setTabOrder(self.box_np40, self.box_pp48)
        QWidget.setTabOrder(self.box_pp48, self.box_nn48)
        QWidget.setTabOrder(self.box_nn48, self.box_nn40)
        QWidget.setTabOrder(self.box_nn40, self.button_findratio)
        QWidget.setTabOrder(self.button_findratio, self.box_pp40)
        QWidget.setTabOrder(self.box_pp40, self.ratio_output)

        self.menubar.addAction(self.menuSettings.menuAction())
        self.menuSettings.addAction(self.actionSettingsConstants)

        self.retranslateUi(MainWindow)

        self.tabDYT.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SRC Ratio Calculator", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionEmbed.setText(QCoreApplication.translate("MainWindow", u"Embed", None))
#if QT_CONFIG(shortcut)
        self.actionEmbed.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionImport_Design.setText(QCoreApplication.translate("MainWindow", u"Import Design", None))
#if QT_CONFIG(shortcut)
        self.actionImport_Design.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport_Design.setText(QCoreApplication.translate("MainWindow", u"Export Design", None))
#if QT_CONFIG(shortcut)
        self.actionExport_Design.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionShow_Errors.setText(QCoreApplication.translate("MainWindow", u"Show Errors", None))
        self.actionShow_Figure.setText(QCoreApplication.translate("MainWindow", u"Show Figure", None))
        self.actionSave_all_Figure.setText(QCoreApplication.translate("MainWindow", u"Save all Figure", None))
        self.actionSave_results_to_HDF5.setText(QCoreApplication.translate("MainWindow", u"Save results to HDF5 ", None))
        self.actionReset_DYT.setText(QCoreApplication.translate("MainWindow", u"Reset DYT", None))
        self.actionSettingsConstants.setText(QCoreApplication.translate("MainWindow", u"Change Constants", None))
        self.actionSave_equil_to_EQDSK.setText(QCoreApplication.translate("MainWindow", u"Save equilibrium to EQDSK", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Insert Pair Numbers", None))
#if QT_CONFIG(whatsthis)
        self.box_np48.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.box_np48.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.box_np48.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.box_np48.setInputMask("")
        self.box_np48.setText("")
        self.box_np48.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.box_nn48.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.box_nn48.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.box_nn48.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.box_nn48.setInputMask("")
        self.box_nn48.setText("")
        self.box_nn48.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.box_np40.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.box_np40.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.box_np40.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.box_np40.setInputMask("")
        self.box_np40.setText("")
        self.box_np40.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.box_nn40.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.box_nn40.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.box_nn40.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.box_nn40.setInputMask("")
        self.box_nn40.setText("")
        self.box_nn40.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.box_pp40.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.box_pp40.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.box_pp40.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.box_pp40.setInputMask("")
        self.box_pp40.setText("")
        self.box_pp40.setPlaceholderText("")
        self.label_np48.setText(QCoreApplication.translate("MainWindow", u"#np48", None))
        self.label_nn48.setText(QCoreApplication.translate("MainWindow", u"#nn48", None))
#if QT_CONFIG(tooltip)
        self.label_np40.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>elongation of the plasma during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_np40.setText(QCoreApplication.translate("MainWindow", u"#np40", None))
#if QT_CONFIG(tooltip)
        self.label_nn40.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>triangularity during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_nn40.setText(QCoreApplication.translate("MainWindow", u"#nn40", None))
#if QT_CONFIG(tooltip)
        self.label_pp40.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Target thermal normalized Beta during the plasma current flat top phase to estimate required heating power. Fast ions are not included.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_pp40.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Normalized Beta</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_pp40.setText(QCoreApplication.translate("MainWindow", u"#pp40", None))
        self.label_pp48.setText(QCoreApplication.translate("MainWindow", u"#pp48", None))
#if QT_CONFIG(whatsthis)
        self.box_pp48.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.box_pp48.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.box_pp48.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.box_pp48.setInputMask("")
        self.box_pp48.setText("")
        self.box_pp48.setPlaceholderText("")
        self.button_findratio.setText(QCoreApplication.translate("MainWindow", u"Find Ratios", None))
        self.buttonSaveRatios.setText(QCoreApplication.translate("MainWindow", u"Save Data", None))
        self.label_RatioName.setText(QCoreApplication.translate("MainWindow", u"Model Name:", None))
        self.btn_clear_1.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.left_1.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.right_1.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.model_label1.setText("")
        self.tabDYT.setTabText(self.tabDYT.indexOf(self.page_general), QCoreApplication.translate("MainWindow", u"Find Ratio", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Insert 5 Ratios (calculates pair numbers , e.g #np48 / #SRC)", None))
#if QT_CONFIG(whatsthis)
        self.Reep.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reep.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reep.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reep.setInputMask("")
        self.Reep.setText("")
        self.Reep.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.Ree.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Ree.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Ree.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Ree.setInputMask("")
        self.Ree.setText("")
        self.Ree.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.Reen.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reen.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reen.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reen.setInputMask("")
        self.Reen.setText("")
        self.Reen.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.Reepp.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reepp.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reepp.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reepp.setInputMask("")
        self.Reepp.setText("")
        self.Reepp.setPlaceholderText("")
        self.label_np48_2.setText(QCoreApplication.translate("MainWindow", u"R(e,e'p)", None))
        self.label_nn48_2.setText(QCoreApplication.translate("MainWindow", u"R(e,e')", None))
#if QT_CONFIG(tooltip)
        self.label_np40_2.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>elongation of the plasma during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_np40_2.setText(QCoreApplication.translate("MainWindow", u"R(e,e'n)", None))
#if QT_CONFIG(tooltip)
        self.label_nn40_2.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>triangularity during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_nn40_2.setText(QCoreApplication.translate("MainWindow", u"R(e,e'pp)", None))
        self.label_pp48_2.setText(QCoreApplication.translate("MainWindow", u"R(e,e'np)", None))
#if QT_CONFIG(whatsthis)
        self.Reenp.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reenp.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reenp.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reenp.setInputMask("")
        self.Reenp.setText("")
        self.Reenp.setPlaceholderText("")
#if QT_CONFIG(tooltip)
        self.label_np40_3.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>elongation of the plasma during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_np40_3.setText(QCoreApplication.translate("MainWindow", u"Ca48(np/n)", None))
#if QT_CONFIG(whatsthis)
        self.ppp40.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.ppp40.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.ppp40.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.ppp40.setInputMask("")
        self.ppp40.setText("")
        self.ppp40.setPlaceholderText("")
#if QT_CONFIG(tooltip)
        self.label_nn40_3.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>triangularity during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_nn40_3.setText(QCoreApplication.translate("MainWindow", u"Ca40(np/n)", None))
#if QT_CONFIG(whatsthis)
        self.ppp48.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.ppp48.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.ppp48.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.ppp48.setInputMask("")
        self.ppp48.setText("")
        self.ppp48.setPlaceholderText("")
        self.label_np48_3.setText(QCoreApplication.translate("MainWindow", u"Ca48(pp/p)", None))
#if QT_CONFIG(whatsthis)
        self.npn40.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.npn40.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.npn40.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.npn40.setInputMask("")
        self.npn40.setText("")
        self.npn40.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.npn48.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.npn48.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.npn48.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.npn48.setInputMask("")
        self.npn48.setText("")
        self.npn48.setPlaceholderText("")
        self.label_nn48_3.setText(QCoreApplication.translate("MainWindow", u"Ca40(pp/p)", None))
        self.button_findpn.setText(QCoreApplication.translate("MainWindow", u"Find Pair Numbers", None))
        self.buttonSavePN.setText(QCoreApplication.translate("MainWindow", u"Save Data", None))
        self.label_NPname.setText(QCoreApplication.translate("MainWindow", u"Model Name:", None))
        self.btn_clear_2.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.left_2.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.right_2.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.tabDYT.setTabText(self.tabDYT.indexOf(self.page_PFcoils), QCoreApplication.translate("MainWindow", u"Find PN (5)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Insert 4 Ratios (calculates pair number ratios - np48/np40, nn48/np40 ...)", None))
#if QT_CONFIG(whatsthis)
        self.Reep_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reep_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reep_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reep_2.setInputMask("")
        self.Reep_2.setText(QCoreApplication.translate("MainWindow", u"1.02", None))
        self.Reep_2.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.Ree_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Ree_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Ree_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Ree_2.setInputMask("")
        self.Ree_2.setText(QCoreApplication.translate("MainWindow", u"1.17", None))
        self.Ree_2.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.Reen_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reen_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reen_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reen_2.setInputMask("")
        self.Reen_2.setText(QCoreApplication.translate("MainWindow", u"1.28", None))
        self.Reen_2.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.Reepp_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reepp_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reepp_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reepp_2.setInputMask("")
        self.Reepp_2.setText("")
        self.Reepp_2.setPlaceholderText("")
        self.label_np48_4.setText(QCoreApplication.translate("MainWindow", u"R(e,e'p)", None))
        self.label_nn48_4.setText(QCoreApplication.translate("MainWindow", u"R(e,e')", None))
#if QT_CONFIG(tooltip)
        self.label_np40_4.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>elongation of the plasma during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_np40_4.setText(QCoreApplication.translate("MainWindow", u"R(e,e'n)", None))
#if QT_CONFIG(tooltip)
        self.label_nn40_4.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>triangularity during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_nn40_4.setText(QCoreApplication.translate("MainWindow", u"R(e,e'pp)", None))
        self.label_pp48_3.setText(QCoreApplication.translate("MainWindow", u"R(e,e'np)", None))
#if QT_CONFIG(whatsthis)
        self.Reenp_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.Reenp_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.Reenp_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.Reenp_2.setInputMask("")
        self.Reenp_2.setText(QCoreApplication.translate("MainWindow", u"1.2", None))
        self.Reenp_2.setPlaceholderText("")
#if QT_CONFIG(tooltip)
        self.label_np40_5.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>elongation of the plasma during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_np40_5.setText(QCoreApplication.translate("MainWindow", u"Ca48(np/n)", None))
#if QT_CONFIG(whatsthis)
        self.ppp40_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.ppp40_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.ppp40_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.ppp40_2.setInputMask("")
        self.ppp40_2.setText("")
        self.ppp40_2.setPlaceholderText("")
#if QT_CONFIG(tooltip)
        self.label_nn40_5.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>triangularity during the plasma current flat top phase</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_nn40_5.setText(QCoreApplication.translate("MainWindow", u"Ca40(np/n)", None))
#if QT_CONFIG(whatsthis)
        self.ppp48_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.ppp48_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.ppp48_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.ppp48_2.setInputMask("")
        self.ppp48_2.setText("")
        self.ppp48_2.setPlaceholderText("")
        self.label_np48_5.setText(QCoreApplication.translate("MainWindow", u"Ca48(pp/p)", None))
#if QT_CONFIG(whatsthis)
        self.npn40_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.npn40_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.npn40_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.npn40_2.setInputMask("")
        self.npn40_2.setText("")
        self.npn40_2.setPlaceholderText("")
#if QT_CONFIG(whatsthis)
        self.npn48_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.npn48_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"majorR", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.npn48_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.npn48_2.setInputMask("")
        self.npn48_2.setText("")
        self.npn48_2.setPlaceholderText("")
        self.label_nn48_5.setText(QCoreApplication.translate("MainWindow", u"Ca40(pp/p)", None))
        self.button_findpn_2.setText(QCoreApplication.translate("MainWindow", u"Find Pair Numbers", None))
        self.buttonSavePN_2.setText(QCoreApplication.translate("MainWindow", u"Save Data", None))
        self.label_NPname_2.setText(QCoreApplication.translate("MainWindow", u"Model Name:", None))
        self.btn_clear_3.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.right_3.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.left_3.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.tabDYT.setTabText(self.tabDYT.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Find PN (4)", None))
        ___qtablewidgetitem = self.pn_table.verticalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Model", None));
        ___qtablewidgetitem1 = self.pn_table.verticalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"#np48", None));
        ___qtablewidgetitem2 = self.pn_table.verticalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"#nn48", None));
        ___qtablewidgetitem3 = self.pn_table.verticalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"#pp48", None));
        ___qtablewidgetitem4 = self.pn_table.verticalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"#np40", None));
        ___qtablewidgetitem5 = self.pn_table.verticalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"#nn40", None));
        ___qtablewidgetitem6 = self.pn_table.verticalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"#pp40", None));
        ___qtablewidgetitem7 = self.pn_table.verticalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"#SRC48 / #SRC40", None));
        ___qtablewidgetitem8 = self.ratio_table.verticalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Model", None));
        ___qtablewidgetitem9 = self.ratio_table.verticalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Ca48/Ca40 (e,e'p)", None));
        ___qtablewidgetitem10 = self.ratio_table.verticalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Ca48/Ca40 (e,e'n)", None));
        ___qtablewidgetitem11 = self.ratio_table.verticalHeaderItem(3)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Ca48/Ca40 (e,e')", None));
        ___qtablewidgetitem12 = self.ratio_table.verticalHeaderItem(4)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Ca48/Ca40 (e,e'np)", None));
        ___qtablewidgetitem13 = self.ratio_table.verticalHeaderItem(5)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Ca48/Ca40 (e,e'pp)", None));
        ___qtablewidgetitem14 = self.ratio_table.verticalHeaderItem(6)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Ca48 (e,e'pp)/(e,e'p)", None));
        ___qtablewidgetitem15 = self.ratio_table.verticalHeaderItem(7)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Ca48 (e,e'np)/(e,e'n)", None));
        ___qtablewidgetitem16 = self.ratio_table.verticalHeaderItem(8)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Ca40 (e,e'pp)/(e,e'p)", None));
        ___qtablewidgetitem17 = self.ratio_table.verticalHeaderItem(9)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Ca40 (e,e'np)/(e,e'n)", None));
        self.label.setText(QCoreApplication.translate("MainWindow", u"Pair Number Values", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Ratio Values", None))
        self.tabDYT.setTabText(self.tabDYT.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Data", None))
        self.rangeEdit.setText("")
        self.graphButton.setText(QCoreApplication.translate("MainWindow", u"Generate Graph", None))
        self.calcType.setCurrentText("")
        self.calcTypeLabel.setText(QCoreApplication.translate("MainWindow", u"Calculation Type:", None))
        self.rangeLabel.setText(QCoreApplication.translate("MainWindow", u"Range:", None))
        self.checkNormAtom.setText(QCoreApplication.translate("MainWindow", u"Normalize Per Nucleus", None))
        self.stepEdit.setText("")
        self.stepLabel.setText(QCoreApplication.translate("MainWindow", u"Step:", None))
        self.exprLabel.setText(QCoreApplication.translate("MainWindow", u"Dependent Var:", None))
        self.exprEdit.setText("")
        self.textEdit.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To create graph, select calculation type, range, and step. When using two independent vars. the two ranges and steps must be inserted with only a comma between them.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dependent variable can be any expression of np48, nn48, etc. (e.g np48/np40)</p>\n"
"<p style=\" m"
                        "argin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To select independent variable (max 2) go to corresponding tab and write T[val] where val is the center value of the range.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(e.g: select calc type Find PN (4), type T[1.2] for R(e,e'np), range=0.2, a d dependent var=pp48/pp40 will give pp48/pp40 as function of R(e,e'np) for values between 1.1 and 1.3)</p></body></html>", None))
        self.button.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.button_2.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.tabDYT.setTabText(self.tabDYT.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Graph", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

